"""Frozen-GIC GF/PED analysis workflows."""

from importlib import import_module

from .harmonic import GFResult, mass_weighted_cartesian_hessian, solve_wilson_gf
from .internal import (
    BOHR_TO_ANGSTROM,
    GFLocalOptions,
    InternalGFResult,
    PEDTable,
    gf_from_cartesian_hessian_and_gic_b_matrix,
    gf_from_cartesian_hessian_and_matrix_gics,
    gf_from_cartesian_hessian_and_oracle_gics,
    gf_from_gaussian_fchk_with_matrix_gics,
    gf_from_gaussian_fchk_with_oracle_gics,
    gf_from_hessian_input_and_gic_definition,
    gf_from_hessian_input_and_xyzin,
    gf_from_hessian_input_with_matrix_gics,
    gf_from_hessian_input_with_oracle_gics,
    gic_labels_from_u,
    local_force_constant_mask,
    primitive_label,
    pulay_scale_internal_hessian,
    topology_bonds_from_xyzin,
)
from .large_amplitude import (
    DEFAULT_LARGE_AMPLITUDE_FAMILIES,
    GFLargeAmplitudeAnalysis,
    LargeAmplitudeBlock,
    LargeAmplitudeCoordinate,
    LargeAmplitudeModeContribution,
    gic_coordinate_family,
    large_amplitude_analysis_from_gf_matrices,
)
from .models import HessianInput
from .nonbonded import (
    nonbonded_cartesian_hessian_correction,
    synthon_charges_from_xyzin,
)
from .sections import (
    GFGICRow,
    GFLargeAmplitudeBlockRow,
    GFLargeAmplitudeCoordinateRow,
    GFLargeAmplitudeModeRow,
    GFModeRow,
    GFPEDSection,
    ORACLE_XYZ_GF_PED_SCHEMA,
    gf_ped_section_from_report,
    gf_ped_section_lines,
    parse_gf_ped_section,
    read_gf_ped_section,
    write_gf_ped_section,
    write_gf_ped_section_from_report,
)

_SERVICE_EXPORTS = {
    "GFFrequencyComparison",
    "GFGeometryComparison",
    "GFScalingAssignment",
    "GFScalingClass",
    "GFScalingPreview",
    "GFScalingRulePreview",
    "GFReport",
    "GFLocalOptions",
    "format_gf_scaling_preview",
    "gf_scaling_preview_from_xyzin",
    "format_gf_report",
    "gf_csv_tables",
    "pulay_scaling_preview",
    "pulay_scaling_factors",
    "run_gf_report_from_fchk",
    "run_xyzin_gf_report_from_fchk",
    "run_xyzin_gf_report_from_xyzin",
    "write_csv_tables",
}


def __getattr__(name: str):
    if name in _SERVICE_EXPORTS:
        return getattr(import_module(".service", __name__), name)
    raise AttributeError(name)


__all__ = [
    "BOHR_TO_ANGSTROM",
    "DEFAULT_LARGE_AMPLITUDE_FAMILIES",
    "GFGICRow",
    "GFFrequencyComparison",
    "GFGeometryComparison",
    "GFLargeAmplitudeAnalysis",
    "GFLargeAmplitudeBlockRow",
    "GFLargeAmplitudeCoordinateRow",
    "GFLargeAmplitudeModeRow",
    "GFLocalOptions",
    "GFModeRow",
    "GFPEDSection",
    "GFReport",
    "GFResult",
    "GFScalingAssignment",
    "GFScalingClass",
    "GFScalingPreview",
    "GFScalingRulePreview",
    "HessianInput",
    "InternalGFResult",
    "LargeAmplitudeBlock",
    "LargeAmplitudeCoordinate",
    "LargeAmplitudeModeContribution",
    "ORACLE_XYZ_GF_PED_SCHEMA",
    "PEDTable",
    "format_gf_report",
    "format_gf_scaling_preview",
    "gf_scaling_preview_from_xyzin",
    "gf_csv_tables",
    "gf_ped_section_from_report",
    "gf_ped_section_lines",
    "gf_from_cartesian_hessian_and_gic_b_matrix",
    "gf_from_cartesian_hessian_and_matrix_gics",
    "gf_from_cartesian_hessian_and_oracle_gics",
    "gf_from_gaussian_fchk_with_matrix_gics",
    "gf_from_gaussian_fchk_with_oracle_gics",
    "gf_from_hessian_input_and_gic_definition",
    "gf_from_hessian_input_and_xyzin",
    "gf_from_hessian_input_with_matrix_gics",
    "gf_from_hessian_input_with_oracle_gics",
    "gic_labels_from_u",
    "gic_coordinate_family",
    "large_amplitude_analysis_from_gf_matrices",
    "local_force_constant_mask",
    "mass_weighted_cartesian_hessian",
    "nonbonded_cartesian_hessian_correction",
    "parse_gf_ped_section",
    "primitive_label",
    "pulay_scale_internal_hessian",
    "pulay_scaling_factors",
    "pulay_scaling_preview",
    "read_gf_ped_section",
    "run_gf_report_from_fchk",
    "run_xyzin_gf_report_from_fchk",
    "run_xyzin_gf_report_from_xyzin",
    "solve_wilson_gf",
    "synthon_charges_from_xyzin",
    "topology_bonds_from_xyzin",
    "write_csv_tables",
    "write_gf_ped_section",
    "write_gf_ped_section_from_report",
]
